#14ej8k Beta menu
fed-team/BridgeIT pull request #10
Opened 2019-07-03 20:05 UTC by NataliaFamulska

2019-07-03 22:30 UTC, dam-orzel requested changes
Cały folder icon jest do wywalenia. Fontello dawno przestało być godnym uwagi narzędziem. O wiele lepszym pomysłem byłoby wykorzystanie font-awesome.
Proszę o poprawienie elementów podanych w komentarzach.

2019-07-03 22:30 UTC, dam-orzel commented on Nav BridgeIT/css/style.css
> +.flexWrapper {
Nie ma sensu dodawać do nazwy klasy słowa "flex". jeżeli wrapper miałby być mieć display: flex nie musi to być aż tak eksponowane.

2019-07-03 22:30 UTC, dam-orzel commented on Nav BridgeIT/css/style.css
> +  position: absolute;
1. Projekt zakłada, że menu będzie "przyklejone" do okna przeglądarki dlatego w tym wypadku nelażałoby dać właściwość fixed.
2. Nawet jeżeli projekt by nie zakładał "przyklejenia" to pozycja absolutna jest i tak zbędna, ponieważ menu i tak będzie pierwszym elementem w drzewie.

2019-07-03 22:30 UTC, dam-orzel commented on Nav BridgeIT/css/style.css
> +.flexMenu{
> Nie ma sensu dodawać do nazwy klasy słowa "flex". jeżeli wrapper miałby być mieć display: flex nie musi to być aż tak eksponowane.

2019-07-03 22:30 UTC, dam-orzel commented on Nav BridgeIT/css/style.css
> +.flexBetween{
> Nie ma sensu dodawać do nazwy klasy słowa "flex". jeżeli wrapper miałby być mieć display: flex nie musi to być aż tak eksponowane.

2019-07-03 22:30 UTC, dam-orzel commented on Nav BridgeIT/css/style.css
> +  .flexMenu{
> Nie ma sensu dodawać do nazwy klasy słowa "flex". jeżeli wrapper miałby być mieć display: flex nie musi to być aż tak eksponowane.

2019-07-03 22:30 UTC, dam-orzel commented on Nav BridgeIT/css/style.css
> +  .flexRow{
Czemu to jest puste?

2019-07-03 22:30 UTC, dam-orzel commented on Nav BridgeIT/css/style.css
> +  .menuItem {
Czemu to jest puste?

2019-07-03 22:30 UTC, dam-orzel commented on Nav BridgeIT/css/style.css
> +  .topLogo {
Czemu to jest puste?

2019-07-03 22:30 UTC, dam-orzel commented on Nav BridgeIT/css/style.css
> +  .flexBetween {
> Nie ma sensu dodawać do nazwy klasy słowa "flex". jeżeli wrapper miałby być mieć display: flex nie musi to być aż tak eksponowane.

2019-07-03 22:30 UTC, dam-orzel commented on Nav BridgeIT/index.html
> +      <ul class="menuItem flexMenu">
Jaki jest cel tych dwóch klas obok siebie? Nie wystarczy samo "flexMenu"?

2019-07-03 22:30 UTC, dam-orzel commented on Nav BridgeIT/index.html
> +    <div class="flexWrapper " id="menu">
id średnio podpowiada o co chodzi. Lepiej dodać tutaj id o nazwie np. menuToggle.

2019-07-03 22:30 UTC, dam-orzel commented on Nav BridgeIT/index.html
> +      <div class="topLogo">
lepsza nazwa dla klasy np. menuLogo. topLogo średnio podpowiada z czym mamy do czynienia.

2019-07-03 22:30 UTC, dam-orzel commented on Nav BridgeIT/index.html
> +      <div class="flexBetween">
flexBetween nie mówi o niczym co się dzieję w środku. Nadaj nazwę odpowiadającom stanowi faktycznemu np. menuButtonBox (oczywiście to tylko przykład ale pokazuje, że od razu wiadomo co znajduje się w tej strukturze)

2019-07-04 14:02 UTC, mras2303 commented
Proszę kontynuować

2019-07-04 14:19 UTC, hayuna requested changes

2019-07-04 14:19 UTC, mras2303 commented on Nav BridgeIT/js/script.js
> +document.getElementById('buttonToogle').onclick = function(){
po kliknięciu w button, dodaje się do niego klasa show, przez co w jednym momencie mamy element z klasami `show` i `hide`
Aby pokazało się menu, trzeba kliknąć button dwa razy
Wydaje mi się, że lepiej gdyby na mobilce pokazywały się elementy w menu domyślnie i bez możliwości ich ukrywania.

2019-07-05 08:42 UTC, mras2303 commented on Nav BridgeIT/js/script.js
> +document.getElementById('buttonToggle').onclick = function(){
>Informacyjnie 

Czy możesz znaleźć informacje czym różnią się zapisy metod używających eventów
- `element.onclick = function(){ ... }`
- `element.click(event => { ... })`
- `element.addEventListener('click', event => { ... })`

2019-07-05 08:46 UTC, mras2303 commented on Nav BridgeIT/index.html
> +      <div class="displayNoneMenu" id="menuToggle">
No nie wiem, kłóciłbym się co do nazw displayNoneMenu, displayShowMenu
Z tego co widzę po nazwie ich jedynym celem jest pokazanie lub niepokazanie menu. Pokombinuj jeszcze raz z bardziej generyczną nazwą typu show/hide ;)

2019-07-05 08:47 UTC, mras2303 commented on Nav BridgeIT/css/style.css
> +.displayNoneMenu, .displayShowMenu{
Oba stany menu mają identyczny styl, może warto dodać go do stylu całego menu

2019-07-05 08:51 UTC, mras2303 commented on Nav BridgeIT/js/script.js
> +  if (menu.className === "displayNoneMenu") {
co jeśli ktoś dodałby klasę do elementu menu? np określającą jej wygląd (.primary)
Twój warunek całkowicie by się wysypał i nigdy if nie zostałby spełniony.
menu.className przechowuje wszystkie klasy elementu oddzielone spacją, z racji tego
jeśli menu będzie miało dwie klasy, Twój warunek wyglądałby tak:
if ("primary displayNoneMenu" === "displayNoneMenu")
lepszym sposobem tutaj będzie szukanie konkretnego tekstu w menu.className lub konwersję klas na tablicę i wyszukania elementu w tablicy

2019-07-05 12:34 UTC, dam-orzel requested changes

2019-07-05 12:34 UTC, dam-orzel commented on Nav BridgeIT/css/style.css
> +  padding: 0.5rem 1rem;
w jednostkach REM pracujemy tylko i wyłącznie przy tekstach i czcionkach.

2019-07-05 12:34 UTC, dam-orzel commented on Nav BridgeIT/css/rwd.css
> +    padding: 1rem 2rem;
> w jednostkach REM pracujemy tylko i wyłącznie przy tekstach i czcionkach.

2019-07-05 12:34 UTC, dam-orzel commented on Nav BridgeIT/css/rwd.css
> +    margin-left: 2rem;
> w jednostkach REM pracujemy tylko i wyłącznie przy tekstach i czcionkach.

2019-07-05 12:34 UTC, dam-orzel commented on Nav BridgeIT/css/rwd.css
> +    margin-right: 2rem;
> w jednostkach REM pracujemy tylko i wyłącznie przy tekstach i czcionkach.

2019-07-05 12:34 UTC, dam-orzel commented on Nav BridgeIT/css/rwd.css
> +    height: 5rem;
> w jednostkach REM pracujemy tylko i wyłącznie przy tekstach i czcionkach.

2019-07-05 14:31 UTC, merged