Section_price
fed-team/BridgeIT pull request #11
Opened 2019-07-03 20:52 UTC by iMuertos

2019-07-03 22:51 UTC, dam-orzel requested changes
Do poprawki pare rzeczy ale ogólnie jest ok.

2019-07-03 22:51 UTC, dam-orzel commented on Section_prices/index.html
> +                <h1>Choose your <span class="blue">plan</span></h1>
Zrób chociaż nazwę textBlue dla klasy. Samo blue jest mało interesujące.

2019-07-03 22:51 UTC, dam-orzel commented on Section_prices/index.html
> +                    <div class="logo"></div>
Wiem, że w Vue każdy komponent to oddzielne style, ale co jeżeli kiedyś zachcę stworzyć globalny styl dla klasy logo? Proszę o nazywanie klas w sposób bardziej szczegółowy. Nie ma problemu aby nazwać klase "priceLogo"

2019-07-03 22:51 UTC, dam-orzel commented on Section_prices/style.css
> +.container {
Wystarczy dodać justify-content: space-between aby uniknąć następnego komentarza...

2019-07-03 22:51 UTC, dam-orzel commented on Section_prices/style.css
> +}
ww komentarz poazwala Ci usunąć te style:
* .price:nth-of-type(1)
* .price:nth-of-type(2)

Flex jest naprawde ciekawym narzędziem i warto z niego korzystać w pełnej okazałości

2019-07-03 22:51 UTC, dam-orzel commented on Section_prices/style.css
> +    font-size: 14px;
pracujemy w rem na font-size. Rozumiem, że pracujesz na własnym index.html, a nie w Vue dlatego to nie błąd, a uwaga. Wszystko jest na ClickUp [https://app.clickup.com/t/14ekda](url)

2019-07-03 22:51 UTC, dam-orzel commented on Section_prices/style.css
> +button.priceStartMiddle {
Nie uważasz, że priceStartMiddle ma większość styli taką samą jak priceStart? Spróbuj to rozwiązać w optymalny sposób

2019-07-03 22:51 UTC, dam-orzel commented on Section_prices/style.css
> +button.priceStart {
po najechaniu na przycisk nic się nie dzieję, gdzie jest cursor: pointer??

2019-07-05 14:14 UTC, dam-orzel approved these changes

2019-07-05 14:23 UTC, mras2303 commented on Section_prices/index.html
> +    <link <link
Masz dwa razy <link

2019-07-05 14:28 UTC, merged